"""empty message

Revision ID: 8d54353bf959
Revises: 88c5ce1477d4
Create Date: 2019-09-02 21:13:34.789172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d54353bf959'
down_revision = '88c5ce1477d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('City', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=15), nullable=True),
    sa.Column('availability_status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('City')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('availability_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user', name='user_pkey')
    )
    op.drop_table('city')
    # ### end Alembic commands ###
